services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sqlctest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_sqlctest:/var/lib/postgresql/data

volumes:
  postgres_data_sqlctest:
